name: Google App Engine Deployment
# For this to work, you must verify the App Engine Admin API is enabled.
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieving the repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
          pip install pytest
          pytest -p no:cacheprovider 
      - name: Run deployment
        if: success()
        uses: actions-hub/gcloud@master
          env:
            PROJECT_ID: ${{ secrets.GCP_PROJECT }}
            APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS  }}
          with:
            args: info
        with:
          entrypoint: gcloud
          args: app deploy ./app.yaml --quiet