name: Integration tests

on: [push]

env:
  working-directory: ./

jobs:
  Pytest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.13
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Upgrade pip
      run: pip install --upgrade pip
    - name: Install Pytest
      run: pip install -r requirements.txt
    - name: Run pytests
      run: pytest -p no:cacheprovider
      working-directory: ${{env.working-directory}}
    - name: Generate coverage report
      run: pytest --cov=./ --cov-report=xml
      working-directory: ${{env.working-directory}}
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3

